
INSERT INTO menu (name, price, distributor, description)
VALUES ('Bread Serious', 6.50, 1, 'turkey, brie, cranberry sauce, and walnuts on rosemary'),
('The Bro-wich', 5.00, 1, 'a-bro-cado and bro-volone cheese toasted on a plain bagel'),
('The Consensu-el', 2.00, 1, 'avocado on a slice of multigrain toast'),
('The Consensu-el (+ bacon)', 3.00, 1, 'avocado and bacon on a slice of multigrain toast'), 
('Darjeeling Limited', 4.50, 1, 'brie and mango chutney on multigrain bread'),
('Darjeeling LImited (+ ham)', 5.50, 1, 'brie, mango chutney, and ham on multigrain bread'), 
('Italiano', 6.00, 1, 'ham, pesto, roasted red pepeprs, and provolone on rosemary garlic bread'), 
('Le Petit Francais', 6.00, 1, 'brie, apple, honey, and walnuts on a croissant'), 
('Murphys Law', 4.50, 1, 'cheddar, avocado, and tomato toasted on rye bread'), 
('Love Snack', 3.50, 1, 'brie + strawberry jam on a croissant'), 
('Sharp n Sweet', 4.50, 1, 'cheddar cheese and fig jam on multigrain bread'), 
('Nutella Croissant', 3.00, 1, ''), 
('Nutella Croissant (+ apple)', 3.50, 1, ''), 
('The Tenure Track', 7.00, 1, 'turkey, artichoke tapenade, sun-dried tomatoes, avocado, and provolone on multigrain bread'), 
('The Tourist', 6.50, 1, 'turkey, avocado, crisp apple slices, and provolone cheese on sourdough bread'), 
('Uh Huh Honey', 4.50, 1, 'muenster, apple, walnuts, and honey on sourdough bread'), 
('The Vegan', 5.00, 1, 'hummus, tomato, avocado, roasted red peppers, and salt & pepper on wheat bread'), 
('Young Money Millionaire', 5.00, 1, 'bagel with cream cheese, avocado, roasted reds, and salt & pepper'), 
('Rosy Roasty Toasty', 4.50, 1, 'goat cheese, tomatoes, roasted red peppers, pesto, and greens on rosemary garlic bread'), 
('Mini Quesadilla', 2.00, 1, '1 gluten free quesadilla'), 
('Mini Quesadillas', 3.00, 1, '2 gluten free quesadillas'), 
('Mini Quesadilla (+ avocado)', 3.00, 1, '1 gluten free quesadilla + avocado'), 
('Mini Quesadillas (+ avocado)', 4.00, 1, '2 gluten free quesadillas + avocado'), 
('DeSombre Side Salad', 3.50, 1, 'greens with sliced apple, chopped walnuts, and goat cheese (gluten free)'), 
('Macintyre Side Salad', 3.50, 1, 'greens with hummus, roasted red peppers, and tomatoes (gluten free)'), 
('Hansu Side Salad', 3.50, 1, 'greens with avocado, sundried tomatoes, and walnuts (gluten free)'), 
('Hansu Side Salad (+ bacon)', 4.50, 1, 'greens with avocado, sundried tomatoes, walnuts, and bacon (gluten free)');